name: 9anime R3NCOD3R

on:
  workflow_dispatch:
    inputs:
      InputMediaURL:
        description: "Stream m3u8 Playlist URL"
        required: true
        default: ""
      AnimeName:
        description: "Name of the Anime w/ space"
        required: true
        default: ""
      InputRes:
        description: "Resolution of Input Playlist"
        required: true
        default: "1080p"
      OutputRes:
        description: "Resolution of Output Video"
        required: true
        default: "576p"
      FrameRate:
        description: "Frame Rate, 24/25"
        required: true
        default: "24"
      AudioType:
        description: "Anime Category, EngSub/EngDub"
        required: true
        default: "EngSub"
      SpeedProf:
        description: "r3ncod3r SpeedProfile, 0/1/2"
        required: true
        default: "1"

env:
  LocationOnIndex: "td:/StreamLoaderZ"
  InputMediaURL: ${{ github.event.inputs.InputMediaURL }}
  AnimeName: ${{ github.event.inputs.AnimeName }}
  InputRes: ${{ github.event.inputs.InputRes }}
  OutputRes: ${{ github.event.inputs.OutputRes }}
  AudioType: ${{ github.event.inputs.AudioType }}
  SpeedProf: ${{ github.event.inputs.SpeedProf }}
  RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}
  RCLONE_INSTALL_MIRROR: ${{ secrets.RCLONE_INSTALL_MIRROR }}
  FTOOL_ARC_URL: ${{ secrets.FTOOL_ARC_URL }}
  FTOOL_CONVERTER: ${{ secrets.FTOOL_CONVERTER }}
  FTOOL_PROBER: ${{ secrets.FTOOL_PROBER }}

jobs:
  transload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Tools
        run: |
          bash ./fftool.sh
      - name: "Anime Transload Job - ${{env.AnimeName}}"
        run: |
          bash ./transload.sh
      - id: set-aud
        run: |
          echo "::set-output name=audlang::${AudLang}"
          echo ${{ steps.set-aud.outputs.audlang }}
      - id: set-matrix
        run: |
          echo "::set-output name=matrix::${matrix}"
          echo ${{ steps.set-matrix.outputs.matrix }}

  encode:
    runs-on: ubuntu-latest
    needs: transload

    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        partnum: ${{ needs.transload.outputs.matrix }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Tools
        run: |
          bash ./fftool.sh
      - name: "Anime R3NCOD3R Job - ${{env.AnimeName}}"
        env:
          partnum: ${{ matrix.partnum }}
        run: |
          bash ./encode.sh

  merge:
    runs-on: ubuntu-latest
    needs: [transload, encode]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Tools
        run: |
          bash ./fftool.sh
      - name: "Anime Merger Job - ${{env.AnimeName}}"
        env:
          AudLang: ${{ needs.transload.outputs.audlang }}
        run: |
          bash ./merge.sh

